- name: Prepare all nodes
  hosts: all
  become: yes
  roles:
    - common

- name: Configure Kubernetes master
  hosts: masters
  become: yes
  roles:
    - kubeadm-master

- name: Configure Kubernetes workers  
  hosts: workers
  become: yes
  roles:
    - kubeadm-worker
